### ISSUE TITLE
File upload via wifi error

### ISSUE THREAD

**Issue by nickrodie** [makerbase-mks/MKS-Robin-Nano-V1.X#40] opened 2020-06-30 13:46 UTC
When I try to upload gcode via wifi from pronterface it fails with `[ERROR] Can't write to printer (disconnected?) (Socket error 10054): An existing connection was forcibly closed by the remote host` and at top right corner of TFT I get `Err5`
Can anyone help?

Nano V1.2 
TFT 35 
Mks_Nano35_V2.0.3.2

**Comment by Engi23** [comment] 2020-07-06 21:55
I use ultimaker cura, Mks_Nano35_V2.0.3.1 it work. Try to place the printer not far from wifi. microSD inserted? The problem is not fully described. Is the printer connected to the wifi? Does the program see the temperature of the extruder, etc.?

**Comment by mks-viva** [comment] 2020-12-01 12:42
I think your plug-in should be updated to the latest. You can check the wifi connection status on Robin TFT35, etc.

**Comment by mks-viva** [comment] 2021-01-18 11:11
Hi! If have not response, i will close this issues temporarily.

**Closed by mks-viva** 2021-01-18 11:11 UTC
